### ISSUE TITLE
Answer cut off when filling in the answers to question 8 of PHP Strings and Variables Quiz

### ISSUE THREAD

**Issue by HBDanks** [Codecademy/client-modules#1540]
When filling in the answers to question 8 of PHP Strings and Variables Quiz, the variable name "$favorite_food" gets cut to just show "$favorite_foo". Fixing this to avoid confusion would be a good improvement to user experience, it doesn't affect the accuracy of their answer.

Computer: MacBook Pro (16-inch, 2019)
Operating System: macOS Catalina 10.15.7
Browser: Safari

<img width="1378" alt="Screen Shot 2021-03-19 at 10 50 17 AM" src="https://user-images.githubusercontent.com/44505134/111822705-5c06e500-88a1-11eb-8bb6-ae2a0653feaa.png">

Note: I was not able to recreate this error on:
MacBook Pro:  Chrome
Surface Pro 7:  Microsoft Edge and Chrome

Accidentally posted in the Events repo, so closed and opened here, where I believe it should be. Please let me know if there is a better repo to raise this issue.

**Comment by JoshuaKGoldberg** [comment]
Hi @HBDanks, thanks for raising this issue! The right place to raise it would be help.codecademy.com.

**Comment by JoshuaKGoldberg** [comment]
@HBDanks good news, we forwarded this around internally and the team that works on those quizzes is taking a look. They've confirmed they can reproduce it (and only in Safari).

Thanks again for the bug report! 🤗
